### ISSUE TITLE
微信小游戏copy出错

### ISSUE THREAD

**Issue by marty0929** [weidian-inc/hera#32]
```
C:\Users\Administrator\Desktop\hero\jump>hera run web
node "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\hera-cli\\n
ode_modules\\weweb-cli\\bin\\weweb"  -b --nocheck -d heraTmp/web
文件将生成到:
C:\Users\Administrator\Desktop\hero\jump\heraTmp\web
Unhandled Rejection at: Promise {
  <rejected> Error: Cannot copy 'C:\Users\Administrator\Desktop\hero\jump' to a
subdirectory of itself, 'C:\Users\Administrator\Desktop\hero\jump\heraTmp\web'.
    at checkDest (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hera-c
li\node_modules\fs-extra\lib\copy\copy.js:146:19)
    at fs.readlink (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hera
-cli\node_modules\fs-extra\lib\copy\copy.js:242:67)
    at FSReqWrap.oncomplete (fs.js:135:15) } reason: Error: Cannot copy 'C:\User
s\Administrator\Desktop\hero\jump' to a subdirectory of itself, 'C:\Users\Admini
strator\Desktop\hero\jump\heraTmp\web'.
    at checkDest (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hera-c
li\node_modules\fs-extra\lib\copy\copy.js:146:19)
    at fs.readlink (C:\Users\Administrator\AppData\Roaming\npm\node_modules\hera
-cli\node_modules\fs-extra\lib\copy\copy.js:242:67)
    at FSReqWrap.oncomplete (fs.js:135:15)
```                     
不知道是不是现在还不支持小游戏的web转换。

**Comment by marty0929** [comment]
用的例子是跳一跳的源码

**Comment by tbfly** [comment]
应该是还不支持 小游戏的web转换。 weweb是基础。
