### ISSUE TITLE
cordova框架无法运行

### ISSUE THREAD

**Issue by YIGENB** [weidian-inc/hera#50]
框架下无法运行X5内核

**Comment by YIGENB** [comment]
E/ReflectionUtils: 'android.webview.chromium.tencent.TencentCookieManagerAdapter' invoke static method 'getInstance' failed
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.common.utils.ReflectionUtils.invokeStaticMethod(TbsJavaCore:246)
        at com.tencent.tbs.tbsshell.common.c.c.a(TbsJavaCore:430)
        at com.tencent.tbs.tbsshell.common.c.c.c(TbsJavaCore:295)
        at com.tencent.tbs.tbsshell.c.a(TbsJavaCore:607)
        at com.tencent.tbs.tbsshell.WebCoreProxy.canUseX5(TbsJavaCore:142)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.smtt.sdk.bl.a(Unknown Source:28)
        at com.tencent.smtt.sdk.bk.a(Unknown Source:45)
        at com.tencent.smtt.sdk.g.run(Unknown Source:38)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'com.tencent.tbs.core.webkit.CookieManager com.tencent.tbs.core.webkit.WebViewFactoryProvider.getCookieManager()' on a null object reference
        at com.tencent.tbs.core.webkit.CookieManager.getInstance(TbsJavaCore:42)
        at android.webview.chromium.tencent.TencentCookieManagerAdapter.getInstance(TbsJavaCore:95)

**Comment by YIGENB** [comment]
E/ReflectionUtils: 'com.tencent.tbs.core.webkit.tencent.TencentCacheManager' invoke static method 'init' failed
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.tencent.common.utils.ReflectionUtils.invokeStaticMethod(TbsJavaCore:246)
        at com.tencent.tbs.tbsshell.common.c.c.a(TbsJavaCore:430)
        at com.tencent.tbs.tbsshell.common.c.c.e(TbsJavaCore:366)
        at com.tencent.tbs.tbsshell.c.a(TbsJavaCore:670)
        at com.tencent.tbs.tbsshell.c$4.doRun(TbsJavaCore:698)
        at com.tencent.common.threadpool.BrowserExecutorSupplier$BackgroundRunable.run(TbsJavaCore:755)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:929)
        at com.tencent.common.threadpool.QBThreadFactory$1.run(TbsJavaCore:47)
     Caused by: java.lang.IllegalAccessError: Method 'java.lang.String org.chromium.base.PathUtils.getDirectoryPath(int)' is inaccessible to class 'org.chromium.tencent.base.TencentPathUtils' (declaration of 'org.chromium.tencent.base.TencentPathUtils' appears in /data/user/0/com.chinaexpressair.portal.test/app_tbs/core_share/tbs_jars_fusion_dex.jar)
        at org.chromium.tencent.base.TencentPathUtils.getDataDirectory(TbsJavaCore:21)
        at com.tencent.tbs.core.webkit.tencent.TencentCacheManager.init(TbsJavaCore:202)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.tencent.common.utils.ReflectionUtils.invokeStaticMethod(TbsJavaCore:246) 
        at com.tencent.tbs.tbsshell.common.c.c.a(TbsJavaCore:430) 
        at com.tencent.tbs.tbsshell.common.c.c.e(TbsJavaCore:366) 
        at com.tencent.tbs.tbsshell.c.a(TbsJavaCore:670) 
        at com.tencent.tbs.tbsshell.c$4.doRun(TbsJavaCore:698) 
        at com.tencent.common.threadpool.BrowserExecutorSupplier$BackgroundRunable.run(TbsJavaCore:755) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:929) 
        at com.tencent.common.threadpool.QBThreadFactory$1.run(TbsJavaCore:47) 
E/Tinker.UncaughtHandler: TinkerUncaughtHandler catch exception:java.lang.NoClassDefFoundError: Failed resolution of: Lcom/facebook/stetho/Stetho;
        at com.weidian.lib.hera.main.HeraService.onCreate(HeraService.java:139)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4634)
        at android.app.ActivityThread.access$2800(ActivityThread.java:308)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2330)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8341)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.stetho.Stetho" on path: DexPathList[[zip file "/data/app/com.chinaexpressair.portal.test-ArRCgvH1OAWVhV8M8TZdLg==/base.apk"],nativeLibraryDirectories=[/data/app/com.chinaexpressair.portal.test-ArRCgvH1OAWVhV8M8TZdLg==/lib/arm, /data/app/com.chinaexpressair.portal.test-ArRCgvH1OAWVhV8M8TZdLg==/base.apk!/lib/armeabi-v7a, /system/lib, /hw_product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.weidian.lib.hera.main.HeraService.onCreate(HeraService.java:139) 
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:4634) 
        at android.app.ActivityThread.access$2800(ActivityThread.java:308) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2330) 
        at android.os.Handler.dispatchMessage(Handler.java:110) 
        at android.os.Looper.loop(Looper.java:219) 
        at android.app.ActivityThread.main(ActivityThread.java:8341) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
